name: Generate Public Assets

on:
  workflow_dispatch:
  push:
    paths:
      - '**.md'
permissions: write-all
env:
  GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
  FEED_TOKEN: ${{ secrets.FEED_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Feed
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://feed.wikip.co/api/memo?openId=${{ env.FEED_TOKEN }}"
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"content": "Hello from github actions"}'
