---
name: 'build docker images'

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPOSITORY#*/}
          TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
      - name: Update Feed
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://feed.wikip.co/api/memo?openId=${{ env.FEED_TOKEN }}"
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"content": "New Docker Image Published (${{ steps.docker-build.outputs.imageid }}): https://hub.docker.com/r/anthonyrussano/wikip-co/tags \n View Image Layers: https://hub.docker.com/layers/anthonyrussano/wikip-co/latest/images/${{ steps.docker-build.outputs.digest }}?context=explore"}'
