name: Generate Public Assets

on:
  workflow_dispatch:
  push:
    paths:
      - '**.md'
permissions: write-all
env:
  GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}
    - name: Update Feed
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://feed.wikip.co/api/memo?openId='
        method: 'POST'
        bearerToken: ${{ secrets.FEED_TOKEN }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"content": "Hello from github actions"}'
